id: PAD43D7EA
initial_creation_type: input
source_metadata:
  title: Siṃhamukhā Series
  language: es
  description: 'Texts related to Siṃhamukhā/Siṃhamukhī or Siṃhavaktrā (seng ge gdong
    ma), the Lion-Faced Ḍākinī:'
  volume:
    c683a422cbf3467686eddfafc8185757:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Averting Obstacles
    16e75123e81f4cb390374108c0ca4613:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: History
    6a8e57df867c48f0908b224b63b6e3b9:
      title: Siṃhamukhā Lineage Prayer
      parent: Lineage Prayers
created_at: '2022-03-01T05:49:02.015814'
last_modified_at: '2022-03-01T05:49:02.015816'
